In [2]:
import os
from pathlib import Path
import pandas as pd
from concurrent.futures import ProcessPoolExecutor
from concurrent.futures import ThreadPoolExecutor

C:\Users\wadia\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [17]:
df_clientes = pd.read_csv('./data/01_raw/01_Tabla_de_Clientes.csv', sep=',', encoding='latin-1')
df_clientes.head()

,cliente_id,edad,genero,region,zona,tipo_cliente,es_digital,uso_app,uso_whatsapp,interaccion_digital_score,canal_whatsapp,canal_sms,canal_llamada,canal_campo,score_riesgo,prob_default,num_atrasos_previos,dias_mora_promedio,ratio_pago,ultimo_pago_dias
0,1,59,F,Lima,urbano,recurrente,0,0.36,1,27,1,1,1,0,375,0.425,2,7,0.67,80
1,2,49,F,Centro,urbano,nuevo,0,0.68,1,67,1,1,1,1,605,0.252,2,50,0.26,52
2,3,35,F,Norte,rural,recurrente,1,0.09,1,56,1,1,1,0,767,0.055,3,21,0.59,81
3,4,63,F,Sur,urbano,nuevo,1,0.38,1,43,1,1,1,0,602,0.147,2,31,0.44,57
4,5,28,M,Lima,urbano,nuevo,1,0.87,1,93,1,1,1,0,737,0.870,2,19,0.15,21

In [16]:
df_creditos = pd.read_csv('./data/01_raw/02_Tabla_de_Crditos.csv', sep=',', encoding='latin-1')
df_creditos.head()

,credito_id,cliente_id,periodo,fecha_corte,producto,saldo_inicial,cuota_mensual,saldo_restante,dias_mora,tramo_mora,estado_credito,pago_realizado_mes,monto_pagado_mes,fecha_pago,prob_pago_7d_base,prob_pago_30d_base,num_creditos_activos
0,1,1,2026-01,2026-01-31,microcredito,4076.98,281.25,3850.56,13,01-30,vigente,1,226.42,2026-01-28,0.183,0.242,1
1,1,1,2026-02,2026-02-28,microcredito,4076.98,281.25,3552.88,0,0,vigente,1,297.68,2026-02-08,0.183,0.242,1
2,1,1,2026-03,2026-03-31,microcredito,4076.98,281.25,3276.21,0,0,vigente,1,276.67,2026-03-03,0.183,0.242,1
3,2,2,2026-01,2026-01-31,negocio,901.40,70.76,815.20,7,01-30,vigente,1,86.20,2026-01-01,0.051,0.250,2
4,2,2,2026-02,2026-02-28,negocio,901.40,70.76,815.20,37,31-60,vigente,0,0.00,NaN,0.051,0.250,2

In [15]:
df_contactos = pd.read_csv('./data/01_raw/03_Tabla_contactos.csv', sep=';', encoding='latin-1')
df_contactos.head()

,contacto_id,cliente_id,credito_id,fecha_contacto,hora_contacto,producto,dias_mora,tramo_mora,saldo_restante,cuota_mensual,...,costo_contacto,prob_pago_7d_post_contacto_modelada,pago_7d_post_contacto,pago_monto_7d,ingreso_esperado,roi_contacto,intensidad_contacto,fatiga_contacto,recency_score,days_since_due
0,1,1,1,7/01/2026,20:15:00,microcredito,0,0,4076.98,281.25,...,1.5,0.164,0,0.0,46.12,29.75,0.000,baja,0.000,0
1,2,1,1,27/01/2026,16:00:00,microcredito,1,1/01/2030 00:00,4071.53,281.25,...,0.2,0.044,0,0.0,12.38,60.90,0.033,baja,0.048,1
2,3,1,1,10/02/2026,17:45:00,microcredito,0,0,4020.05,281.25,...,0.1,0.394,0,0.0,110.81,1107.10,0.067,baja,0.067,0
3,4,1,1,17/02/2026,19:15:00,microcredito,0,0,4006.28,281.25,...,1.5,0.164,0,0.0,46.12,29.75,0.100,baja,0.125,0
4,5,1,1,18/02/2026,15:30:00,microcredito,0,0,4027.13,281.25,...,1.5,0.124,0,0.0,34.88,22.25,0.133,media,0.500,0